# Generated by Django 5.1.6 on 2025-02-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('air_quality', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
            ],
        ),
    ]
